trigger:
- main

pool:
  vmImage: ubuntu-latest
  name: default

variables:
  majorVersion: '1'
  minorVersion: '0'
  artifactVersion: ''

steps:
- checkout: self
  clean: true

- script: dotnet pack -p Version=1.0.$(Build.BuildId)
  displayName: 'build the artifact'

- script: |
    major_version=${env:majorVersion}
    minor_version=${env:minorVersion}
    build_number=$(Build.BuildNumber)
    new_version="$major_version.$minor_version.$build_number"
    echo "New artifact version: $new_version"
    artifactVersion="$new_version"
  displayName: 'Increment Version (Bash)'

- publish: $(System.DefaultWorkingDirectory)/bin/Release/net8.0/HelloWorldApp.dll
  artifact: helloworld