trigger:
- master

pool:
  vmImage: ubuntu-latest
  name: default

variables:
  majorVersion: '1'
  minorVersion: '0'
  artifactVersion: ''

steps:
- checkout: self
  clean: true


- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'azure_devops_pipeline_connection_master'
    scannerMode: 'MSBuild'
    projectKey: 'azure_devops_pipeline_azure_devops_pipeline_a8ba4cd5-8197-48c3-bcce-45500f7bf955'

# Dotnet build task
- script: dotnet pack -p Version=1.0.$(Build.BuildId)
  displayName: 'build the artifact'

# Run Code Analysis task
- task: SonarQubeAnalyze@5
  inputs:
    jdkversion: 'JAVA_HOME'
    
# Publish Quality Gate Result task
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'

- script: |
    major_version=${env:majorVersion}
    minor_version=${env:minorVersion}
    build_number=$(Build.BuildNumber)
    new_version="$major_version.$minor_version.$build_number"
    echo "New artifact version: $new_version"
    artifactVersion="$new_version"
  displayName: 'Increment Version (Bash)'

- publish: $(System.DefaultWorkingDirectory)/HelloWorldApp/bin/Release/net8.0/HelloWorldApp.dll
  artifact: helloworld